### ISSUE TITLE
When auto click left turn on, game crashes

### ISSUE THREAD

**Issue by futag** [breelock/AutoClicky#1]
java.lang.NoSuchFieldError: Class net.minecraft.class_5134 does not have member field 'net.minecraft.class_1320 field_23723'
	at com.breelock.autoclicky.PlayerMethods.getAttackSpeedInTicks(PlayerMethods.java:164)
	at com.breelock.autoclicky.PlayerMethods.attack(PlayerMethods.java:31)
	at com.breelock.autoclicky.AutoClicky.lambda$onInitialize$0(AutoClicky.java:80)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$bff000$fabric-lifecycle-events-v1$onStartTick(class_310.java:7178)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by breelock** [comment]
What version of the game are you using?

**Comment by futag** [comment]
Mod ver: 1.2.1
Fabric loder ver: 0.16.3
Minecraft ver: 1.21.1

**Comment by breelock** [comment]
Thanks for reporting the issue! It has been fixed. You can download the fixed mod version for minecraft 1.20.5-1.21.1 here: [GitHub releases](https://github.com/breelock/AutoClicky/releases/tag/v1.2.1), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/autoclicky/files/5681644), [Modrinth](https://modrinth.com/mod/autoclicky/version/5Gb6x5fa)
